### ISSUE TITLE
Pre-release versions added to the main channel

### ISSUE THREAD

**Issue by m-rossi** [conda-forge/sqlacodegen-feedstock#11]
### *Resolution*

Yanking the pre-release packages would cause more disruption than keeping them.

If you're here because you pulled in a 3.0.0 pre-release when you didn't intent to (perhaps because you had no upper-bound or used `<3.0.0`) you will need to pin this package to either `~=2.3` or `<3.0.0a0`

----
### Comment:

I just saw you pushed pre-releases (3.0.0b2) to main channel. May we should use the official approach for adding pre-release builds? https://conda-forge.org/docs/maintainer/knowledge_base.html#pre-release-builds

If you create an `rc` branch I can create a PR for a pre-release package.

**Comment by beckermr** [comment]
cc @conda-forge/core We need to address this one way or the other.

@conda-forge/sqlacodegen Can you explain what is happening here?

**Comment by dhirschfeld** [comment]
> Maybe we should use the official approach for adding pre-release builds?

That's probably a good idea.

> Can you explain what is happening here?

I published `sqlacodegen` to `conda-forge` because I had need of it and I published version `3.0.0b2` because I needed features from the new version.

As @m-rosi says, that perhaps should have been done following CEP-05 but at the time I don't think I was really aware of that. The `sqlacodegen` "pre-release" phase is a multi-year pre-release in the spirit of [`marshmallow 3`](https://pypi.org/project/marshmallow/#history) which was the precedent I was aware of and following at the time.

Although publishing to an `rc` branch might have been better I don't see too much real harm in having published `3.0.0b2`. `sqlacodegen` is a small CLI package used by very few people. Publishing the pre-release to the `main` branch simply *defaults* users to pulling in the new version. If people don't want to pull in the next major version they can easily enough pin to `~=2.0` or `<3.0.0a0`.

**Comment by dhirschfeld** [comment]
I'm happy to make any change you'd like, but I'd recommend doing nothing here as I don't see any benefit to doing so. Nobody is really being inconvenienced by this (or they're not so put out as to open an issue) whereas yanking the already published packages would inconvenience all the users who have been happily using the "pre-release" version 3 for the last 18 months.

**Comment by beckermr** [comment]
Thank you for the explanation here. I am surprised to see a pre-release build take so long to reach a full release. I'm ok making an exception in this case, but others from core should weigh in.

**Comment by dhirschfeld** [comment]
> I am surprised to see a pre-release build take so long to reach a full release

It's a one-man side/hobby project. It still ticks over, but slowly. I think the pre-release label is Alex not wanting to commit to no further breaking changes before he's happy with the new api. If there are breaking changes, that would be awkward for all those who I have unwittingly opted-into the pre-release version. OTOH if there aren't any breaking changes, all those users will have been saved from porting to the new api and Alex from having to support a larger userbase on the legacy api. Swings & roundabouts.

I saw the message on the conda gitter, and yeah, for those wanting to explicitly stay on the old version it is slightly awkward having `<3` pull in a 3 pre-release but I think that's a general `conda` gotcha and those in the know pin to `~=2.0` or `3.0.0a0`.

---

> *those in the know pin to `~=2.0` or `3.0.0a0`*

It definitely would have been better if users didn't have to know about that detail and that's a good argument to not publish pre-releases to the `main` channel. Unfortunately here we are. I'll take it on board to follow CEP-05 in future but I don't know that there's any way to "fix" this that won't cause more pain than asking users who want to stay on the legacy api to pin to `<3.0.0a0`.

**Comment by dhirschfeld** [comment]
Again though, happy to make any changes that `conda-forge/core` deem appropriate...

**Comment by ndevenish** [comment]
> I saw the message on the conda gitter, and yeah, for those wanting to explicitly stay on the old version it is slightly awkward having `<3` pull in a 3 pre-release but I think that's a general `conda` gotcha and those in the know pin to `~=2.0` or `3.0.0a0`.

Yes, mainly this was confusion over whether we had just been doing it wrong and needed to change all of our pins to e.g. `package<3dev`, or if this was a bug in conda[^1] (that almost certainly would have been seen before).

Since it's only this package, and we now know, it's not really any trouble.

[^1]: PEP-440 specifies that prereleases are [excluded](https://peps.python.org/pep-0440/#handling-of-pre-releases), and it works this way in pip - to my reading the conda documentation [claims](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/pkg-specs.html#package-match-specifications) that it follows PEP-440; but apparently that is only intended to be read as for strictly the comparison operators.

**Comment by hmaarrfk** [comment]
As a member of core, I think that conda-forge, for better or for worse for those that have built it up, now has a wider reaching audience.

Often, I find it helpful to get help from the upstream developers. I think that releasing software to a wide reaching audience for pre-release builds as "the default installation" often goes against the upstream developer's intention.

I typically suggest that people that need really bleeding edge features, maintain their own conda channels for these kinds of special patches and needs. These channels make their special version of the package "less wide spread" and alleviate alot of the concerns about conda-forge changing things that would break existing environments.

I think that, if narrow in scope, it is up to the individual maintainers how to release these RC packages (main channel or not). If this becomes wider spread, maybe conda-forge core needs to get more involved.

I really lean to:

* Just fork the feedstock repo
* Setup azure.
* Upload to your channel at will.
* Merge back into conda-forge when upstream is ready.

**Comment by dopplershift** [comment]
I'd say if it's been this way for 18 months, making changes to adhere to cfep5 for the last published packages would be more disruptive. But going forward, this should adhere to the standard practice with a separate branch & label. The current pre-release packages could have the appropriate label added to facilitate some migration if that's at all helpful.

To @hmaarrfk's point, I think of the `dev`/`rc` labels as a way for developers to get things out for testing to a wider audience rather than some kind of way for people to get access to bleeding edge features for normal day-to-day work. Regardless, we need to take the upstream maintainers at their word: if it's a pre-release (alpha, beta, release candidate), it's not yet ready for prime time and has no business being on the `main` label; we don't want users who haven't opted into it to get things that aren't declared "ready". (Whether in an open source world these are meaningfully different than us packaging the 0.0.2 release of a package is interesting to ponder.)

**Comment by dhirschfeld** [comment]
I agree with @hmaarrfk that conda-forge is growing up and part of that is striving towards more consistent and professional standards in packaging. The CEPs exist for a reason and I should have followed them. All I can say is sorry, and I'll ensure that I follow them going forward.

In this particular instance, since the pre-release packages have been around for a long time I agree with @dopplershift that pulling them would be more disruptive so I propose to close this issue as a `wontfix`.

3.0.0 will eventually be published and as all users (not already opted into the beta) move to it this issue will (hopefully) become a historical anomaly. In the interim, I'll direct all users wanting to stick with version 2 to pin to `~=2.0` or `<3.0.0a0`.

Please let me know if there are any objections to this plan of action (i.e. closing this a `wontfix`).
